import { StyleSheet } from "react-native";
import { colors, radius, spacing } from "@/theme";
import { withAlpha } from "@/lib/color";

export const styles = StyleSheet.create({
  full: { flex: 1, backgroundColor: colors.bg },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.xs,
    paddingBottom: spacing.sm,
  },
  iconBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  centerContent: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: spacing.x2,
  },
  privacyNotice: {
    marginTop: spacing.lg,
    marginHorizontal: spacing.x2,
    padding: spacing.md,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
  },
  content: { padding: spacing.lg, paddingBottom: spacing.x3 },
  previewImage: {
    width: "100%",
    height: 220,
    borderRadius: radius.md,
    backgroundColor: colors.surface2,
  },
  smallPreview: {
    width: "100%",
    height: 140,
    borderRadius: radius.md,
    backgroundColor: colors.surface2,
  },
  reviewImage: {
    width: "100%",
    height: 180,
    borderRadius: radius.md,
    backgroundColor: colors.surface2,
    marginBottom: spacing.sm,
  },
  optionCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
  },
  optionActive: {
    borderColor: withAlpha(colors.accent, 0.55),
    backgroundColor: withAlpha(colors.accent, 0.07),
  },
  pickRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
  },
  pickRowActive: {
    borderColor: withAlpha(colors.accent, 0.55),
    backgroundColor: withAlpha(colors.accent, 0.07),
  },
  check: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: colors.accent,
    alignItems: "center",
    justifyContent: "center",
  },
  confBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    backgroundColor: withAlpha(colors.accent, 0.08),
    borderRadius: radius.sm,
    alignSelf: "flex-start",
    marginTop: spacing.sm,
  },
  flagBox: {
    marginTop: spacing.md,
    padding: spacing.md,
    backgroundColor: withAlpha(colors.draw, 0.08),
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: withAlpha(colors.draw, 0.2),
  },
  scoreRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    marginTop: spacing.sm,
  },
  stepper: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm,
    marginTop: spacing.sm,
    maxWidth: "100%",
  },
  stepBtn: {
    width: 38,
    height: 38,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface2,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  prefillHint: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    padding: spacing.sm,
    marginBottom: spacing.md,
    borderRadius: radius.sm,
    backgroundColor: withAlpha(colors.accent, 0.07),
  },
  statEditRow: { flexDirection: "row", alignItems: "center", gap: spacing.sm },
  statEditFields: { flex: 1, flexDirection: "row", alignItems: "center", gap: spacing.sm },
  scoreInput: {
    flex: 1,
    minWidth: 0,
    maxWidth: 72,
    textAlign: "center",
    fontFamily: "JetBrainsMono_700Bold",
    fontSize: 34,
    paddingVertical: 2,
  },
  statInput: {
    flex: 1,
    color: colors.text,
    fontSize: 13.5,
    fontFamily: "JetBrainsMono_500Medium",
    backgroundColor: colors.bg,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: radius.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: 8,
    textAlign: "center",
  },
  statsGrid: { flexDirection: "row", flexWrap: "wrap", gap: spacing.md },
  statPair: { flex: 1, minWidth: 100, gap: 4 },
  reviewScore: { flexDirection: "row", alignItems: "center", gap: spacing.sm },
  divider: { height: 1, backgroundColor: colors.line, marginVertical: spacing.lg },
  reviewBottom: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  sourceTag: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    marginTop: spacing.md,
    alignSelf: "center",
  },
  resultBurst: {
    width: 88,
    height: 88,
    borderRadius: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  progressHeader: { paddingHorizontal: spacing.lg, paddingVertical: spacing.sm },
  track: { flexDirection: "row", gap: 5, paddingHorizontal: spacing.lg, marginBottom: spacing.sm },
  trackSeg: { flex: 1, height: 3, borderRadius: 2, backgroundColor: colors.surface2 },
  trackSegOn: { backgroundColor: colors.accent },
  footer: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    paddingBottom: spacing.sm,
    borderTopWidth: 1,
    borderTopColor: colors.line,
    backgroundColor: colors.bg,
  },
});
