import { StyleSheet } from "react-native";
import { colors, radius, spacing } from "@/theme";
import { withAlpha } from "@/lib/color";

export const styles = StyleSheet.create({
  headerRow: {
    minHeight: 52,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    paddingVertical: spacing.sm,
  },
  headerRowDesktop: { minHeight: 64, paddingTop: spacing.x2, paddingBottom: spacing.md },
  modeSwitch: { marginTop: spacing.md, alignItems: "flex-start" },
  stepTitle: { marginBottom: spacing.sm },
  lede: { lineHeight: 19, marginBottom: spacing.lg },
  // Consent
  consentLoading: { alignItems: "center", paddingTop: spacing.x4 },
  consentPoints: { gap: spacing.lg, marginTop: spacing.x2 },
  consentPoint: { flexDirection: "row", gap: spacing.md },
  policyLink: { alignSelf: "center", marginTop: spacing.lg, paddingVertical: spacing.xs },
  // Capture
  captureHero: { alignItems: "center", paddingTop: spacing.x2 },
  captureIcon: {
    width: 72,
    height: 72,
    borderRadius: 36,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: withAlpha(colors.accent, 0.1),
    borderWidth: 1,
    borderColor: withAlpha(colors.accent, 0.25),
  },
  dropZone: {
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.md,
    minHeight: 300,
    padding: spacing.x3,
    borderWidth: 2,
    borderStyle: "dashed",
    borderColor: colors.lineStrong,
    borderRadius: radius.xl,
    backgroundColor: colors.surface,
  },
  dropZoneActive: {
    borderColor: colors.accent,
    backgroundColor: withAlpha(colors.accent, 0.06),
  },
  kbd: {
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: colors.lineStrong,
    backgroundColor: colors.surface2,
  },
  fakeButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: spacing.sm,
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: radius.md,
    backgroundColor: colors.accent,
  },
  captureActions: { gap: spacing.md, width: "100%", maxWidth: 420, alignSelf: "center" },
  privacyNotice: {
    marginTop: spacing.x2,
    padding: spacing.md,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
    flexDirection: "row",
    gap: spacing.sm,
  },
  // Processing
  scanFrame: {
    width: "100%",
    maxWidth: 520,
    height: 260,
    alignSelf: "center",
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface2,
    overflow: "hidden",
  },
  scanImage: { width: "100%", height: "100%", opacity: 0.85 },
  scanLine: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    height: 46,
  },
  scanBeam: { position: "absolute", left: 0, right: 0, bottom: 0, height: 2 },
  checklist: {
    gap: spacing.md,
    marginTop: spacing.x2,
    width: "100%",
    maxWidth: 360,
    alignSelf: "center",
  },
  checkRow: { flexDirection: "row", alignItems: "center", gap: spacing.md },
  checkDot: {
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.line,
  },
  checkDotDone: { backgroundColor: colors.accent, borderColor: colors.accent },
  checkDotActive: { borderColor: withAlpha(colors.accent, 0.6) },
  // Steps
  optionCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
  },
  optionActive: {
    borderColor: withAlpha(colors.accent, 0.55),
    backgroundColor: withAlpha(colors.accent, 0.07),
  },
  sideBadge: {
    width: 44,
    height: 44,
    borderRadius: radius.sm,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surface2,
  },
  phoneThumb: { marginBottom: spacing.lg },
  confBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    backgroundColor: withAlpha(colors.accent, 0.08),
    borderRadius: radius.sm,
    alignSelf: "flex-start",
    marginTop: spacing.sm,
  },
  flagBox: {
    marginTop: spacing.md,
    padding: spacing.md,
    backgroundColor: withAlpha(colors.draw, 0.08),
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: withAlpha(colors.draw, 0.2),
  },
  sectionLabel: { letterSpacing: 1.2, marginBottom: spacing.sm },
  scoreRow: { flexDirection: "row", alignItems: "flex-end", gap: spacing.xs },
  scoreSide: { flex: 1, alignItems: "center", minWidth: 0 },
  prefillHint: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    padding: spacing.sm,
    paddingHorizontal: spacing.md,
    marginBottom: spacing.lg,
    borderRadius: radius.sm,
    backgroundColor: withAlpha(colors.accent, 0.07),
  },
  statHead: { flexDirection: "row", alignItems: "center", marginBottom: spacing.xs },
  statEditRow: { flexDirection: "row", alignItems: "center", gap: spacing.sm },
  statLabel: { width: 118 },
  statEditFields: { flex: 1, flexDirection: "row", alignItems: "center", gap: spacing.sm },
  statInput: {
    flex: 1,
    minWidth: 0,
    fontSize: 14,
    fontFamily: "JetBrainsMono_500Medium",
    backgroundColor: colors.bg,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: radius.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: 9,
    textAlign: "center",
  },
  eloLine: { flexDirection: "row", alignItems: "baseline" },
  kicker: { letterSpacing: 1.2 },
  sourceTag: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    marginTop: spacing.md,
  },
  // Chrome
  track: { flexDirection: "row", gap: 5, marginTop: spacing.xs },
  trackSeg: {
    flex: 1,
    height: 3,
    borderRadius: 2,
    backgroundColor: colors.surface2,
    overflow: "hidden",
  },
  trackFill: { height: "100%", borderRadius: 2, backgroundColor: colors.accent },
  footer: {
    paddingTop: spacing.md,
    paddingBottom: spacing.sm,
    borderTopWidth: 1,
    borderTopColor: colors.line,
    backgroundColor: colors.bg,
  },
  footerDesktop: { paddingBottom: spacing.lg },
  footerRow: { flexDirection: "row", alignItems: "center", gap: spacing.sm },
});
